
spring:
    datasource:
      url: jdbc:mysql://localhost:3306/drones
      username: fullstop
      password: 619619
    jpa:
      hibernate:
        ddl-auto: create
    properties:
      hibernate:
        dialect:
          org:
            hibernate:
              dialect: MySQL8Dialect
        format_sql: true

